#!/bin/bash

set -e           # exit on error
set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o errexit   # exit the script if any statement returns a non-true return value

function cleanup {
    echo "Cleaning up..."
    if [ -z ${TMPDIR+x} ] ; then
        echo -n
    else
        rm -rf $TMPDIR
        unset TMPDIR
    fi
}

function error {
    local parent_lineno="$1"
    local message="$2"
    local code="${3:-1}"
    if [[ -n "$message" ]] ; then
        echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
    else
        echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
    fi
    cleanup
    exit "${code}"
}
trap 'error ${LINENO}' ERR

function usage_error {
    echo mongo-sync: "$1"
    echo "usage: mongo-sync push|pull"
    echo ""
    exit
}

function config_not_found {
    echo "failed: '$1' not found, it needs to be in the same dir"
    echo "aborting..."
    echo ""
    exit
}

function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

function get_script_dir {
    pushd . > /dev/null
    local SCRIPT_PATH="${BASH_SOURCE[0]}"

    if ([ -h "${SCRIPT_PATH}" ]) then
      while ([ -h "${SCRIPT_PATH}" ]) do cd `dirname "$SCRIPT_PATH"`; SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
    fi

    cd `dirname ${SCRIPT_PATH}` > /dev/null
    local SCRIPT_PATH=`pwd`;
    popd  > /dev/null

    echo $SCRIPT_PATH
}

function get_confirmation() {
    read -p "Are you sure you want to $1? Enter 'yes': " mongo_confr

    case $mongo_confr in
        [yY][Ee][Ss] )  ;;
        *) echo "Incorrect input, aborting..."; exit;;
    esac
}

function load_configs {
    echo "load_configs"
    if [ -z "$CONFIG_FILE" ] ; then
        CONFIG_FILE="config.yml"
    fi
    local config=$CONFIG_FILE
    echo "Parsing '$config'..."

    DIR=$(get_script_dir)
    local FILE="$DIR/$config"

    if [ -f $FILE ]; then
       eval $(parse_yaml $FILE)
       success_msg
    else
       config_not_found $config
    fi

    # Loads:
    # - $local_db
    # - $local_host_port
    # - $remote_db
    # - $remote_host_url
    # - $remote_host_port
    # - $remote_access_username
    # - $remote_access_password

    TMPDIR=/tmp/"$local_db"/dump
}

function banner {
    echo mongo-sync:
    echo -----------
}

function success_msg {
    echo "Success!"
    echo 
}

function done_msg {
    echo "Done!"
    echo 
}


function pull {
    banner
    get_confirmation 'pull'
    load_configs

    echo "Dumping Remote DB to $TMPDIR... "
    mongodump \
        -h "$remote_host_url":"$remote_host_port" \
        -d "$remote_db" \
        -u "$remote_access_username" \
        -p "$remote_access_password" \
        -o "$TMPDIR" > /dev/null
    success_msg

    echo "Overwriting Local DB... "
    mongorestore -d "$local_db" --port "$local_host_port" "$TMPDIR"/"$remote_db" --drop > /dev/null
    success_msg

    cleanup
    done_msg
}

function push {
    banner
    get_confirmation 'push'
    load_configs
    
    echo "Dumping Local DB to $TMPDIR... "
    mongodump -d "$local_db" --port "$local_host_port" -o "$TMPDIR" > /dev/null
    success_msg

    echo "Overwriting Remote DB with Dump... "
    mongorestore \
        -h "$remote_host_url":"$remote_host_port" \
        -d "$remote_db" \
        -u "$remote_access_username" \
        -p "$remote_access_password" \
        "$TMPDIR"/"$local_db" --drop > /dev/null
    success_msg

    cleanup
    done_msg
}


## MAIN
## ====

# TODO: Add --overwrite flag

if [[ $# -eq 0 ]] ; then
    usage_error "no arguments provided"
else
    if [ "$2" == '--config' ] ; then
        if [ -e "$3" ] ; then
            CONFIG_FILE="$3"
        else
            usage_error "No config file named \"$3\""
        fi
    fi

    if [[ "$1" == 'push' ]] ; then
        push
    elif [[ "$1" == 'pull' ]] ; then
        pull
    else
        usage_error "unrecognized command \"$1\""
    fi
fi
